auth_servers:
  servers:
    -
      id: 0
      cert: /cert/forwarder-0.crt
      cert_key: /cert/forwarder-0.key
    -
      id: 1
      cert: /cert/forwarder-1.crt
      cert_key: /cert/forwarder-1.key

storage_servers:
  client_cert: /cert/client.crt
  client_key: /cert/client.key
  server_cert: /cert/server.crt
  server_key: /cert/server.key

  servers:
    -
      id: 0
      bind_on: "0.0.0.0:40002"
      addr: "127.0.0.1:40002"
      http_bind_on: "0.0.0.0:40003"
      http_addr: "127.0.0.1:40003"
      http_cert: /cert/storage-0.crt
      http_cert_key: /cert/storage-0.key
      folder: "/var/storage_server"

db:
  client_cert: /cert/client.crt
  client_key: /cert/client.key
  server_cert: /cert/server.crt
  server_key: /cert/server.key

  paxos:
    client_cert: /cert/client.crt
    client_key: /cert/client.key
    server_cert: /cert/server.crt
    server_key: /cert/server.key

  servers:
    -
      id: 0
      server_name: "db-0"
      paxos_addr:       "127.0.0.1:20001"
      db_addr:          "127.0.0.1::30001"
      paxos_bind_on:    "0.0.0.0:20001"
      db_bind_on:       "0.0.0.0:30001"
      paxos_folder:     "/var/dstore/db-0/paxos"
      db_folder:        "/var/dstore/db-0/db"
    -
      id: 1
      server_name: "db-1"
      paxos_addr:       "0.0.0.0:20002"
      db_addr:          "0.0.0.0:30002"
      paxos_folder:     "/var/dstore/db-1/paxos"
      db_folder:        "/var/dstore/db-1/db"
    -
      id: 2
      server_name: "db-2"
      paxos_addr:       "0.0.0.0:20003"
      db_addr:          "0.0.0.0:30003"
      paxos_folder:     "/var/dstore/db-2/paxos"
      db_folder:        "/var/dstore/db-2/db"
