// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.17.1
// source: storage_server.proto

package StorageServer

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RegUserReadArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserToken string   `protobuf:"bytes,1,opt,name=UserToken,proto3" json:"UserToken,omitempty"`
	FileToken []string `protobuf:"bytes,2,rep,name=FileToken,proto3" json:"FileToken,omitempty"`
	FileKey   []string `protobuf:"bytes,3,rep,name=FileKey,proto3" json:"FileKey,omitempty"`
}

func (x *RegUserReadArgs) Reset() {
	*x = RegUserReadArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegUserReadArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegUserReadArgs) ProtoMessage() {}

func (x *RegUserReadArgs) ProtoReflect() protoreflect.Message {
	mi := &file_storage_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegUserReadArgs.ProtoReflect.Descriptor instead.
func (*RegUserReadArgs) Descriptor() ([]byte, []int) {
	return file_storage_server_proto_rawDescGZIP(), []int{0}
}

func (x *RegUserReadArgs) GetUserToken() string {
	if x != nil {
		return x.UserToken
	}
	return ""
}

func (x *RegUserReadArgs) GetFileToken() []string {
	if x != nil {
		return x.FileToken
	}
	return nil
}

func (x *RegUserReadArgs) GetFileKey() []string {
	if x != nil {
		return x.FileKey
	}
	return nil
}

type RegUserReadReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileSize string `protobuf:"bytes,1,opt,name=FileSize,proto3" json:"FileSize,omitempty"`
	OK       bool   `protobuf:"varint,2,opt,name=OK,proto3" json:"OK,omitempty"`
	Message  string `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *RegUserReadReply) Reset() {
	*x = RegUserReadReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegUserReadReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegUserReadReply) ProtoMessage() {}

func (x *RegUserReadReply) ProtoReflect() protoreflect.Message {
	mi := &file_storage_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegUserReadReply.ProtoReflect.Descriptor instead.
func (*RegUserReadReply) Descriptor() ([]byte, []int) {
	return file_storage_server_proto_rawDescGZIP(), []int{1}
}

func (x *RegUserReadReply) GetFileSize() string {
	if x != nil {
		return x.FileSize
	}
	return ""
}

func (x *RegUserReadReply) GetOK() bool {
	if x != nil {
		return x.OK
	}
	return false
}

func (x *RegUserReadReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UploadInitArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserToken string   `protobuf:"bytes,1,opt,name=UserToken,proto3" json:"UserToken,omitempty"`
	FileKey   []string `protobuf:"bytes,2,rep,name=FileKey,proto3" json:"FileKey,omitempty"`
	FileSize  []int64  `protobuf:"varint,3,rep,packed,name=FileSize,proto3" json:"FileSize,omitempty"`
	FileToken []string `protobuf:"bytes,4,rep,name=FileToken,proto3" json:"FileToken,omitempty"`
}

func (x *UploadInitArgs) Reset() {
	*x = UploadInitArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadInitArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadInitArgs) ProtoMessage() {}

func (x *UploadInitArgs) ProtoReflect() protoreflect.Message {
	mi := &file_storage_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadInitArgs.ProtoReflect.Descriptor instead.
func (*UploadInitArgs) Descriptor() ([]byte, []int) {
	return file_storage_server_proto_rawDescGZIP(), []int{2}
}

func (x *UploadInitArgs) GetUserToken() string {
	if x != nil {
		return x.UserToken
	}
	return ""
}

func (x *UploadInitArgs) GetFileKey() []string {
	if x != nil {
		return x.FileKey
	}
	return nil
}

func (x *UploadInitArgs) GetFileSize() []int64 {
	if x != nil {
		return x.FileSize
	}
	return nil
}

func (x *UploadInitArgs) GetFileToken() []string {
	if x != nil {
		return x.FileToken
	}
	return nil
}

type UploadInitReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OK      bool   `protobuf:"varint,1,opt,name=OK,proto3" json:"OK,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *UploadInitReply) Reset() {
	*x = UploadInitReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadInitReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadInitReply) ProtoMessage() {}

func (x *UploadInitReply) ProtoReflect() protoreflect.Message {
	mi := &file_storage_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadInitReply.ProtoReflect.Descriptor instead.
func (*UploadInitReply) Descriptor() ([]byte, []int) {
	return file_storage_server_proto_rawDescGZIP(), []int{3}
}

func (x *UploadInitReply) GetOK() bool {
	if x != nil {
		return x.OK
	}
	return false
}

func (x *UploadInitReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UploadFinishArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OldFileKey string `protobuf:"bytes,1,opt,name=OldFileKey,proto3" json:"OldFileKey,omitempty"`
	UserToken  string `protobuf:"bytes,2,opt,name=UserToken,proto3" json:"UserToken,omitempty"`
	FileToken  string `protobuf:"bytes,3,opt,name=FileToken,proto3" json:"FileToken,omitempty"`
	NewFileKey string `protobuf:"bytes,4,opt,name=NewFileKey,proto3" json:"NewFileKey,omitempty"`
	FileSHA512 string `protobuf:"bytes,5,opt,name=FileSHA512,proto3" json:"FileSHA512,omitempty"`
}

func (x *UploadFinishArgs) Reset() {
	*x = UploadFinishArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadFinishArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFinishArgs) ProtoMessage() {}

func (x *UploadFinishArgs) ProtoReflect() protoreflect.Message {
	mi := &file_storage_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFinishArgs.ProtoReflect.Descriptor instead.
func (*UploadFinishArgs) Descriptor() ([]byte, []int) {
	return file_storage_server_proto_rawDescGZIP(), []int{4}
}

func (x *UploadFinishArgs) GetOldFileKey() string {
	if x != nil {
		return x.OldFileKey
	}
	return ""
}

func (x *UploadFinishArgs) GetUserToken() string {
	if x != nil {
		return x.UserToken
	}
	return ""
}

func (x *UploadFinishArgs) GetFileToken() string {
	if x != nil {
		return x.FileToken
	}
	return ""
}

func (x *UploadFinishArgs) GetNewFileKey() string {
	if x != nil {
		return x.NewFileKey
	}
	return ""
}

func (x *UploadFinishArgs) GetFileSHA512() string {
	if x != nil {
		return x.FileSHA512
	}
	return ""
}

type UploadFinishReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OK      bool   `protobuf:"varint,1,opt,name=OK,proto3" json:"OK,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *UploadFinishReply) Reset() {
	*x = UploadFinishReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadFinishReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFinishReply) ProtoMessage() {}

func (x *UploadFinishReply) ProtoReflect() protoreflect.Message {
	mi := &file_storage_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFinishReply.ProtoReflect.Descriptor instead.
func (*UploadFinishReply) Descriptor() ([]byte, []int) {
	return file_storage_server_proto_rawDescGZIP(), []int{5}
}

func (x *UploadFinishReply) GetOK() bool {
	if x != nil {
		return x.OK
	}
	return false
}

func (x *UploadFinishReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_storage_server_proto protoreflect.FileDescriptor

var file_storage_server_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x67, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x61, 0x64, 0x41, 0x72, 0x67, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x55, 0x73, 0x65,
	0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x46, 0x69, 0x6c, 0x65, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x46, 0x69, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x46, 0x69, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x22, 0x58,
	0x0a, 0x10, 0x52, 0x65, 0x67, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x4f, 0x4b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x4f, 0x4b, 0x12, 0x18,
	0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x82, 0x01, 0x0a, 0x0e, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x49, 0x6e, 0x69, 0x74, 0x41, 0x72, 0x67, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x55,
	0x73, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x55, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x46, 0x69, 0x6c,
	0x65, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x46, 0x69, 0x6c, 0x65,
	0x4b, 0x65, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x09, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x3b, 0x0a,
	0x0f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x4b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x4f, 0x4b,
	0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xae, 0x01, 0x0a, 0x10, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x41, 0x72, 0x67, 0x73, 0x12,
	0x1e, 0x0a, 0x0a, 0x4f, 0x6c, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x4f, 0x6c, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x12,
	0x1c, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x55, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x0a,
	0x09, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x4e,
	0x65, 0x77, 0x46, 0x69, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x4e, 0x65, 0x77, 0x46, 0x69, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x46,
	0x69, 0x6c, 0x65, 0x53, 0x48, 0x41, 0x35, 0x31, 0x32, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x48, 0x41, 0x35, 0x31, 0x32, 0x22, 0x3d, 0x0a, 0x11, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x4b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x4f, 0x4b,
	0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x8a, 0x02, 0x0a, 0x0b, 0x46,
	0x69, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x53, 0x0a, 0x10, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x61, 0x64, 0x12, 0x1e,
	0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52,
	0x65, 0x67, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x61, 0x64, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x1f,
	0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52,
	0x65, 0x67, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x4f, 0x0a, 0x0e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x69,
	0x74, 0x12, 0x1d, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6e, 0x69, 0x74, 0x41, 0x72, 0x67, 0x73,
	0x1a, 0x1e, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x55, 0x0a, 0x10, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x46, 0x69,
	0x6e, 0x69, 0x73, 0x68, 0x12, 0x1f, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6e, 0x69, 0x73,
	0x68, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x20, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6e, 0x69,
	0x73, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x1e, 0x5a, 0x1c, 0x64, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_storage_server_proto_rawDescOnce sync.Once
	file_storage_server_proto_rawDescData = file_storage_server_proto_rawDesc
)

func file_storage_server_proto_rawDescGZIP() []byte {
	file_storage_server_proto_rawDescOnce.Do(func() {
		file_storage_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_storage_server_proto_rawDescData)
	})
	return file_storage_server_proto_rawDescData
}

var file_storage_server_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_storage_server_proto_goTypes = []interface{}{
	(*RegUserReadArgs)(nil),   // 0: StorageServer.RegUserReadArgs
	(*RegUserReadReply)(nil),  // 1: StorageServer.RegUserReadReply
	(*UploadInitArgs)(nil),    // 2: StorageServer.UploadInitArgs
	(*UploadInitReply)(nil),   // 3: StorageServer.UploadInitReply
	(*UploadFinishArgs)(nil),  // 4: StorageServer.UploadFinishArgs
	(*UploadFinishReply)(nil), // 5: StorageServer.UploadFinishReply
}
var file_storage_server_proto_depIdxs = []int32{
	0, // 0: StorageServer.FileService.RegisterUserRead:input_type -> StorageServer.RegUserReadArgs
	2, // 1: StorageServer.FileService.UploadFileInit:input_type -> StorageServer.UploadInitArgs
	4, // 2: StorageServer.FileService.UploadFileFinish:input_type -> StorageServer.UploadFinishArgs
	1, // 3: StorageServer.FileService.RegisterUserRead:output_type -> StorageServer.RegUserReadReply
	3, // 4: StorageServer.FileService.UploadFileInit:output_type -> StorageServer.UploadInitReply
	5, // 5: StorageServer.FileService.UploadFileFinish:output_type -> StorageServer.UploadFinishReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_storage_server_proto_init() }
func file_storage_server_proto_init() {
	if File_storage_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_storage_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegUserReadArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegUserReadReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadInitArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadInitReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadFinishArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_server_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadFinishReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_storage_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_server_proto_goTypes,
		DependencyIndexes: file_storage_server_proto_depIdxs,
		MessageInfos:      file_storage_server_proto_msgTypes,
	}.Build()
	File_storage_server_proto = out.File
	file_storage_server_proto_rawDesc = nil
	file_storage_server_proto_goTypes = nil
	file_storage_server_proto_depIdxs = nil
}
